[toolchain]
package_manager = "yarn"
anchor_version = "0.28.0"
solana_version = "1.16.0"

[features]
resolution = true
skip-lint = true
seeds = false

[programs.localnet]
datasold = "7f2vK2P7uWAQY6QS7P8jPhQvbrs6F1BSc4zdejQrcSRn"

[programs.devnet]
datasold = "7f2vK2P7uWAQY6QS7P8jPhQvbrs6F1BSc4zdejQrcSRn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "anchor build"
deploy = "anchor deploy"
start = "anchor start"

[build]
command = "cargo build-sbf --locked --target-dir target"
